steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --context=git://github.com/chuangw6/kaniko-demo.git
  - --destination=gcr.io/chuangw-test/kaniko-tom
  - --cache=true
  - --cache-ttl=8h
