---

apiVersion: v1
kind: Pod
metadata:
  generateName: kaniko-
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:aca3b966a3376c998f4824162912ba5ea04c9d4f
    args: ["--context=git://github.com/chuangw6/kaniko-demo.git",
            "--destination=gcr.io/chuangw-test/kaniko-demo:1.0.0"]
    # volumeMounts:
    #   - name: kaniko-secret
    #     mountPath: /kaniko/.docker
  restartPolicy: Never
  # volumes:
  #   - name: kaniko-secret
  #     secret:
  #       secretName: registry-credentials
  #       items:
  #         - key: .dockerconfigjson
  #           path: config.json

